name: Fossa

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - 'examples/**'
      - '**.md'

concurrency:
  group: ${{ github.ref_name }}-fossa
  cancel-in-progress: true

jobs:

  scan:
    name: Fossa
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Scan
        uses: fossas/fossa-action@v1
        with:
          api-key: ${{ secrets.FOSSA_TOKEN }}
